### ISSUE TITLE
ansible-lint fails with json.decoder.JSONDecodeError in the latest v0.18.0 docker image

### ISSUE THREAD

**Issue by martinkroupa** [ansible/creator-ee#337]
In the latest version of quay.io/ansible/creator-ee:v0.18.0 image, the package dependencies are not correct and the ansible-lint command fails.

**Steps to reproduce the error:**
```shell
$ docker run -it --rm --name ansible-lint -v ./:/test -w /test quay.io/ansible/creator-ee:v0.18.0 bash -c 'ansible-lint; echo $?'
Traceback (most recent call last):
  File "/usr/local/bin/ansible-lint", line 8, in <module>
    sys.exit(_run_cli_entrypoint())
             ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/ansiblelint/__main__.py", line 310, in _run_cli_entrypoint
    sys.exit(main(sys.argv))
             ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/ansiblelint/__main__.py", line 258, in main
    app = get_app()
          ^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/ansiblelint/app.py", line 387, in get_app
    app.runtime.prepare_environment(
  File "/usr/local/lib/python3.11/site-packages/ansiblelint/_vendor/ansible_compat/runtime.py", line 560, in prepare_environment
    self.load_collections()
  File "/usr/local/lib/python3.11/site-packages/ansiblelint/_vendor/ansible_compat/runtime.py", line 176, in load_collections
    data = json.loads(proc.stdout)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
1
```

**After upgrading the component, it is fine:**
```shell
$ docker run -it --rm --name yamllint-test -v ./:/test -w /test quay.io/ansible/creator-ee:v0.18.0 bash -c 'pip3 install -U ansible-compat ansible-runner ansible-lint ansible-core; ansible-lint; echo $?'
```

**Difference between versions:**
```shell
# Before pip3 install
ansible-compat      4.1.2
ansible-core        2.15.0
ansible-lint        6.17.1
ansible-runner      2.3.3

# After pip3 install
ansible-compat      3.0.2
ansible-core        2.15.0
ansible-lint        6.16.1
ansible-runner      2.3.2
```

When upgrading via pip3 there is also an error on dependency conflicts in the log.
`ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
molecule 5.0.1 requires ansible-compat<4.0.0,>=2.2.0, but you have ansible-compat 4.1.2 which is incompatible.`

**Comment by ssbarnea** [comment]
This was fixed in newer versions.
